### ISSUE TITLE
Ruby Gems 

### ISSUE THREAD

**Issue by efferifick** [rubyomr-preview/ruby#96]
Hi, 

I've been running Ruby with OMR always with the `--disable-gems` flag. I'm trying to run a script that requires some ruby gems. However, when I attempt to run this ruby script without the `--disable-gems` flag I get the following error message:

```
$ \
OMR_JIT_OPTIONS=-Xjit:count=1,tracefull,log=logname,optlevel=warm,verbose \
LD_LIBRARY_PATH=".." \
../ruby snake.rb
<internal:gem_prelude>:4:in `require': cannot load such file -- rubygems.rb (LoadError)
	from <internal:gem_prelude>:4:in `<internal:gem_prelude>'
```

I was wondering if this is a known issue. Thanks.

**Comment by mgaudet** [comment]
This is more of a known issue when developing Ruby; Without `make install`ing ruby, you can't use gems. 

See [this bug](https://bugs.ruby-lang.org/issues/6906). 

A word of caution however: If you do install Ruby+OMR, it will preferentially load the JIT from the install directory over the local directory, even with `LD_LIRBARY_PATH` set. This can be _crazy_ confusing.

**Comment by efferifick** [comment]
Awesome! Thanks!
